#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Carl Zeiss Microscopy GmbH
#
# SPDX-License-Identifier: MIT

"""Generate the release SPDX SBOM from explicit project metadata.

The release archives contain statically linked C++ binaries. Generic binary or
directory scanners do not reliably recover statically linked components such as
libCZI, OpenCV, CLI11, GSL, or RapidJSON from the final executable. This helper
therefore creates a small, reviewable SPDX 2.3 JSON document from
``sbom-components.json`` and the files staged for a release artifact.

The generated SBOM is intentionally conservative: it lists the direct
dependencies that the project declares or knowingly links, records file
checksums for the release package contents, and leaves unpinned package-manager
versions as ``NOASSERTION``. Transitive dependency capture from vcpkg, apt, and
apk should be added separately once those inputs are pinned or exported in a
machine-readable form.

Components may be restricted to selected release targets with either exact
``platforms`` entries or ``platformPrefixes`` entries in the metadata file.
Exact platform names are useful for targets with a stable identifier, such as
``alpine-linux-x64`` or ``windows-arm64``. Prefixes are used for target families
whose full identifier is detected from the build runner, such as
``ubuntu-24.04-x64``. This keeps the metadata accurate today while avoiding a
future edit when the pinned Ubuntu runner is intentionally advanced.

The application package version is read from ``CMakeLists.txt`` when
``--project-version-file`` is provided. This keeps the CMake project version as
the single source of truth while still allowing the static metadata file to
describe supplier, license, and dependency information.

The file inventory intentionally excludes packaging files generated by this
release workflow, such as the SBOM itself and ``SHA256SUMS``. This keeps the
payload file set stable whether the generator runs in a fresh directory or in a
directory that already contains outputs from an earlier packaging attempt.
"""

import argparse
import datetime
import hashlib
import json
import pathlib
import re


PACKAGING_GENERATED_FILES = {"SHA256SUMS"}


def spdx_id(value):
    value = value.replace("++", "plusplus").replace("+", "plus")
    normalized = re.sub(r"[^A-Za-z0-9.-]+", "-", value).strip("-")
    return f"SPDXRef-{normalized}"


def file_checksum(path, algorithm):
    digest = hashlib.new(algorithm.lower())
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def package_verification_code(file_sha1s):
    digest = hashlib.sha1()
    for file_sha1 in sorted(file_sha1s):
        digest.update(file_sha1.encode("ascii"))
    return digest.hexdigest()


def include_component(component, platform):
    """Return whether a component belongs in the SBOM for ``platform``.

    ``platforms`` contains exact target identifiers. ``platformPrefixes`` is a
    small escape hatch for build targets whose versioned identifier is detected
    at build time, for example an Ubuntu runner label derived from
    /etc/os-release.
    """
    platforms = component.get("platforms", [])
    platform_prefixes = component.get("platformPrefixes", [])
    return (
        (not platforms and not platform_prefixes)
        or platform in platforms
        or any(platform.startswith(prefix) for prefix in platform_prefixes)
    )


def parse_component_versions(values):
    # Workflows can override versionInfo with values detected from the actual
    # build environment so the generated SBOM reflects what was really linked,
    # not just the conservative defaults tracked in sbom-components.json.
    versions = {}
    for value in values:
        name, separator, version = value.partition("=")
        if not separator or not name.strip() or not version.strip():
            raise ValueError(
                "Component version overrides must use the form "
                "'Component Name=version'."
            )
        versions[name.strip()] = version.strip()
    return versions


def parse_cmake_project_version(path):
    """Extract the project VERSION value from a CMakeLists.txt file."""
    cmake = path.read_text(encoding="utf-8")
    match = re.search(
        r"project\s*\(\s*czi-pyramidizer\b.*?\bVERSION\s+([0-9]+(?:\.[0-9]+)*)",
        cmake,
        re.IGNORECASE | re.DOTALL,
    )
    if not match:
        raise ValueError(f"Unable to determine czi-pyramidizer version from {path}.")
    return match.group(1)


def package_from_component(component, version_overrides):
    package = {
        "name": component["name"],
        "SPDXID": spdx_id(f"Package-{component['name']}"),
        # Prefer CI-detected versions when available. This keeps the metadata
        # file reviewable while still allowing platform-specific builds to
        # publish concrete versions for dependencies such as OpenCV or OpenSSL.
        "versionInfo": version_overrides.get(
            component["name"], component.get("version", "NOASSERTION")
        ),
        "supplier": component.get("supplier", "NOASSERTION"),
        "downloadLocation": component.get("downloadLocation", "NOASSERTION"),
        "filesAnalyzed": False,
        "licenseConcluded": component.get("licenseConcluded", "NOASSERTION"),
        "licenseDeclared": component.get("licenseDeclared", "NOASSERTION"),
        "copyrightText": component.get("copyrightText", "NOASSERTION"),
        "primaryPackagePurpose": component.get("purpose", "LIBRARY"),
    }
    return package


def main():
    parser = argparse.ArgumentParser(
        description="Generate a simple SPDX JSON SBOM from project release metadata."
    )
    parser.add_argument("--metadata", required=True, type=pathlib.Path)
    parser.add_argument("--artifact-dir", required=True, type=pathlib.Path)
    parser.add_argument("--artifact-name", required=True)
    parser.add_argument("--platform", required=True)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument(
        "--project-version-file",
        type=pathlib.Path,
        help=(
            "Read the czi-pyramidizer version from the project VERSION in this "
            "CMakeLists.txt file."
        ),
    )
    parser.add_argument(
        "--component-version",
        action="append",
        default=[],
        help=(
            "Override the versionInfo for a named component, for example "
            "'OpenCV=4.10.0'. Repeat for multiple components."
        ),
    )
    args = parser.parse_args()

    metadata = json.loads(args.metadata.read_text(encoding="utf-8"))
    version_overrides = parse_component_versions(args.component_version)
    if args.project_version_file:
        version_overrides.setdefault(
            "czi-pyramidizer", parse_cmake_project_version(args.project_version_file)
        )
    created = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0)
    document_id = spdx_id(f"DocumentRoot-{args.artifact_name}")

    root_package = {
        "name": args.artifact_name,
        "SPDXID": document_id,
        "supplier": metadata["document"].get("supplier", "NOASSERTION"),
        "downloadLocation": metadata["document"].get(
            "downloadLocation", "NOASSERTION"
        ),
        "filesAnalyzed": True,
        "licenseConcluded": "NOASSERTION",
        "licenseDeclared": "NOASSERTION",
        "copyrightText": "NOASSERTION",
        "primaryPackagePurpose": "ARCHIVE",
    }
    packages = [root_package]

    component_packages = [
        package_from_component(component, version_overrides)
        for component in metadata["components"]
        if include_component(component, args.platform)
    ]
    packages.extend(component_packages)

    files = []
    relationships = [
        {
            "spdxElementId": "SPDXRef-DOCUMENT",
            "relationshipType": "DESCRIBES",
            "relatedSpdxElement": document_id,
        }
    ]

    file_sha1s = []
    output_path = args.output.resolve()
    for path in sorted(args.artifact_dir.iterdir()):
        if (
            not path.is_file()
            or path.resolve() == output_path
            or path.name in PACKAGING_GENERATED_FILES
        ):
            continue
        file_sha1 = file_checksum(path, "sha1")
        file_sha1s.append(file_sha1)
        file_id = spdx_id(f"File-{path.name}")
        files.append(
            {
                "fileName": path.name,
                "SPDXID": file_id,
                "checksums": [
                    {
                        "algorithm": "SHA1",
                        "checksumValue": file_sha1,
                    },
                    {
                        "algorithm": "SHA256",
                        "checksumValue": file_checksum(path, "sha256"),
                    }
                ],
                "licenseConcluded": "NOASSERTION",
                "licenseInfoInFiles": ["NOASSERTION"],
                "copyrightText": "NOASSERTION",
            }
        )
        relationships.append(
            {
                "spdxElementId": document_id,
                "relationshipType": "CONTAINS",
                "relatedSpdxElement": file_id,
            }
        )

    root_package["packageVerificationCode"] = {
        "packageVerificationCodeValue": package_verification_code(file_sha1s)
    }

    app_id = spdx_id("Package-czi-pyramidizer")
    for package in component_packages:
        relationships.append(
            {
                "spdxElementId": document_id,
                "relationshipType": "CONTAINS",
                "relatedSpdxElement": package["SPDXID"],
            }
        )
        if package["SPDXID"] == app_id:
            continue
        relationships.append(
            {
                "spdxElementId": app_id,
                "relationshipType": "DEPENDS_ON",
                "relatedSpdxElement": package["SPDXID"],
            }
        )

    document = {
        "spdxVersion": "SPDX-2.3",
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "name": args.artifact_name,
        "documentNamespace": (
            "https://github.com/ZEISS/czi-pyramidizer/sbom/"
            f"{args.artifact_name}-{created.strftime('%Y%m%d%H%M%S')}"
        ),
        "creationInfo": {
            "creators": [
                "Organization: Carl Zeiss Microscopy GmbH",
                "Tool: czi-pyramidizer-generate-spdx-sbom",
            ],
            "created": created.isoformat().replace("+00:00", "Z"),
        },
        "packages": packages,
        "files": files,
        "relationships": relationships,
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
